// flow-typed signature: b8c94f62161125420fff3d449bfc4889
// flow-typed version: <<STUB>>/babelify_v^8.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babelify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babelify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babelify/index' {
  declare module.exports: $Exports<'babelify'>;
}
declare module 'babelify/index.js' {
  declare module.exports: $Exports<'babelify'>;
}
