// flow-typed signature: 6cd40640b24a0d4328d13719f85db313
// flow-typed version: <<STUB>>/radium_v^0.24.0/flow_v0.44.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'radium'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'radium' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'radium/dist/radium' {
  declare module.exports: any;
}

declare module 'radium/dist/radium.min' {
  declare module.exports: any;
}

declare module 'radium/es/append-important-to-each-value' {
  declare module.exports: any;
}

declare module 'radium/es/append-px-if-needed' {
  declare module.exports: any;
}

declare module 'radium/es/camel-case-props-to-dash-case' {
  declare module.exports: any;
}

declare module 'radium/es/clean-state-key' {
  declare module.exports: any;
}

declare module 'radium/es/components/style-root' {
  declare module.exports: any;
}

declare module 'radium/es/components/style-sheet' {
  declare module.exports: any;
}

declare module 'radium/es/components/style' {
  declare module.exports: any;
}

declare module 'radium/es/config' {
  declare module.exports: any;
}

declare module 'radium/es/css-rule-set-to-string' {
  declare module.exports: any;
}

declare module 'radium/es/enhancer' {
  declare module.exports: any;
}

declare module 'radium/es/get-radium-style-state' {
  declare module.exports: any;
}

declare module 'radium/es/get-state-key' {
  declare module.exports: any;
}

declare module 'radium/es/get-state' {
  declare module.exports: any;
}

declare module 'radium/es/hash' {
  declare module.exports: any;
}

declare module 'radium/es/index' {
  declare module.exports: any;
}

declare module 'radium/es/keyframes' {
  declare module.exports: any;
}

declare module 'radium/es/map-object' {
  declare module.exports: any;
}

declare module 'radium/es/merge-styles' {
  declare module.exports: any;
}

declare module 'radium/es/plugins/check-props-plugin' {
  declare module.exports: any;
}

declare module 'radium/es/plugins/index' {
  declare module.exports: any;
}

declare module 'radium/es/plugins/keyframes-plugin' {
  declare module.exports: any;
}

declare module 'radium/es/plugins/merge-style-array-plugin' {
  declare module.exports: any;
}

declare module 'radium/es/plugins/mouse-up-listener' {
  declare module.exports: any;
}

declare module 'radium/es/plugins/prefix-plugin' {
  declare module.exports: any;
}

declare module 'radium/es/plugins/remove-nested-styles-plugin' {
  declare module.exports: any;
}

declare module 'radium/es/plugins/resolve-interaction-styles-plugin' {
  declare module.exports: any;
}

declare module 'radium/es/plugins/resolve-media-queries-plugin' {
  declare module.exports: any;
}

declare module 'radium/es/plugins/visited-plugin' {
  declare module.exports: any;
}

declare module 'radium/es/prefix-data/dynamic' {
  declare module.exports: any;
}

declare module 'radium/es/prefix-data/static' {
  declare module.exports: any;
}

declare module 'radium/es/prefixer' {
  declare module.exports: any;
}

declare module 'radium/es/resolve-styles' {
  declare module.exports: any;
}

declare module 'radium/es/style-keeper' {
  declare module.exports: any;
}

declare module 'radium/es/test-helpers' {
  declare module.exports: any;
}

declare module 'radium/lib/append-important-to-each-value' {
  declare module.exports: any;
}

declare module 'radium/lib/append-px-if-needed' {
  declare module.exports: any;
}

declare module 'radium/lib/camel-case-props-to-dash-case' {
  declare module.exports: any;
}

declare module 'radium/lib/clean-state-key' {
  declare module.exports: any;
}

declare module 'radium/lib/components/style-root' {
  declare module.exports: any;
}

declare module 'radium/lib/components/style-sheet' {
  declare module.exports: any;
}

declare module 'radium/lib/components/style' {
  declare module.exports: any;
}

declare module 'radium/lib/config' {
  declare module.exports: any;
}

declare module 'radium/lib/css-rule-set-to-string' {
  declare module.exports: any;
}

declare module 'radium/lib/enhancer' {
  declare module.exports: any;
}

declare module 'radium/lib/get-radium-style-state' {
  declare module.exports: any;
}

declare module 'radium/lib/get-state-key' {
  declare module.exports: any;
}

declare module 'radium/lib/get-state' {
  declare module.exports: any;
}

declare module 'radium/lib/hash' {
  declare module.exports: any;
}

declare module 'radium/lib/index' {
  declare module.exports: any;
}

declare module 'radium/lib/keyframes' {
  declare module.exports: any;
}

declare module 'radium/lib/map-object' {
  declare module.exports: any;
}

declare module 'radium/lib/merge-styles' {
  declare module.exports: any;
}

declare module 'radium/lib/plugins/check-props-plugin' {
  declare module.exports: any;
}

declare module 'radium/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'radium/lib/plugins/keyframes-plugin' {
  declare module.exports: any;
}

declare module 'radium/lib/plugins/merge-style-array-plugin' {
  declare module.exports: any;
}

declare module 'radium/lib/plugins/mouse-up-listener' {
  declare module.exports: any;
}

declare module 'radium/lib/plugins/prefix-plugin' {
  declare module.exports: any;
}

declare module 'radium/lib/plugins/remove-nested-styles-plugin' {
  declare module.exports: any;
}

declare module 'radium/lib/plugins/resolve-interaction-styles-plugin' {
  declare module.exports: any;
}

declare module 'radium/lib/plugins/resolve-media-queries-plugin' {
  declare module.exports: any;
}

declare module 'radium/lib/plugins/visited-plugin' {
  declare module.exports: any;
}

declare module 'radium/lib/prefix-data/dynamic' {
  declare module.exports: any;
}

declare module 'radium/lib/prefix-data/static' {
  declare module.exports: any;
}

declare module 'radium/lib/prefixer' {
  declare module.exports: any;
}

declare module 'radium/lib/resolve-styles' {
  declare module.exports: any;
}

declare module 'radium/lib/style-keeper' {
  declare module.exports: any;
}

declare module 'radium/lib/test-helpers' {
  declare module.exports: any;
}

declare module 'radium/src/__mocks__/exenv' {
  declare module.exports: any;
}

declare module 'radium/src/__mocks__/prefixer' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/camel-case-props-to-dash-case-test' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/clean-state-key-test' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/enhancer-test' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/get-radium-style-state-test' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/get-state-key-test' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/get-state-test' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/keyframes-test' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/media-query-test' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/radium-test' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/remove-nested-styles-test' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/resolve-styles-test' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/style-component-test' {
  declare module.exports: any;
}

declare module 'radium/src/__tests__/visited-test' {
  declare module.exports: any;
}

declare module 'radium/src/append-important-to-each-value' {
  declare module.exports: any;
}

declare module 'radium/src/append-px-if-needed' {
  declare module.exports: any;
}

declare module 'radium/src/camel-case-props-to-dash-case' {
  declare module.exports: any;
}

declare module 'radium/src/clean-state-key' {
  declare module.exports: any;
}

declare module 'radium/src/components/style-root' {
  declare module.exports: any;
}

declare module 'radium/src/components/style-sheet' {
  declare module.exports: any;
}

declare module 'radium/src/components/style' {
  declare module.exports: any;
}

declare module 'radium/src/config' {
  declare module.exports: any;
}

declare module 'radium/src/css-rule-set-to-string' {
  declare module.exports: any;
}

declare module 'radium/src/enhancer' {
  declare module.exports: any;
}

declare module 'radium/src/get-radium-style-state' {
  declare module.exports: any;
}

declare module 'radium/src/get-state-key' {
  declare module.exports: any;
}

declare module 'radium/src/get-state' {
  declare module.exports: any;
}

declare module 'radium/src/hash' {
  declare module.exports: any;
}

declare module 'radium/src/index' {
  declare module.exports: any;
}

declare module 'radium/src/keyframes' {
  declare module.exports: any;
}

declare module 'radium/src/map-object' {
  declare module.exports: any;
}

declare module 'radium/src/merge-styles' {
  declare module.exports: any;
}

declare module 'radium/src/plugins/check-props-plugin' {
  declare module.exports: any;
}

declare module 'radium/src/plugins/index' {
  declare module.exports: any;
}

declare module 'radium/src/plugins/keyframes-plugin' {
  declare module.exports: any;
}

declare module 'radium/src/plugins/merge-style-array-plugin' {
  declare module.exports: any;
}

declare module 'radium/src/plugins/mouse-up-listener' {
  declare module.exports: any;
}

declare module 'radium/src/plugins/prefix-plugin' {
  declare module.exports: any;
}

declare module 'radium/src/plugins/remove-nested-styles-plugin' {
  declare module.exports: any;
}

declare module 'radium/src/plugins/resolve-interaction-styles-plugin' {
  declare module.exports: any;
}

declare module 'radium/src/plugins/resolve-media-queries-plugin' {
  declare module.exports: any;
}

declare module 'radium/src/plugins/visited-plugin' {
  declare module.exports: any;
}

declare module 'radium/src/prefix-data/dynamic' {
  declare module.exports: any;
}

declare module 'radium/src/prefix-data/static' {
  declare module.exports: any;
}

declare module 'radium/src/prefixer' {
  declare module.exports: any;
}

declare module 'radium/src/resolve-styles' {
  declare module.exports: any;
}

declare module 'radium/src/style-keeper' {
  declare module.exports: any;
}

declare module 'radium/src/test-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'radium/dist/radium.js' {
  declare module.exports: $Exports<'radium/dist/radium'>;
}
declare module 'radium/dist/radium.min.js' {
  declare module.exports: $Exports<'radium/dist/radium.min'>;
}
declare module 'radium/es/append-important-to-each-value.js' {
  declare module.exports: $Exports<'radium/es/append-important-to-each-value'>;
}
declare module 'radium/es/append-px-if-needed.js' {
  declare module.exports: $Exports<'radium/es/append-px-if-needed'>;
}
declare module 'radium/es/camel-case-props-to-dash-case.js' {
  declare module.exports: $Exports<'radium/es/camel-case-props-to-dash-case'>;
}
declare module 'radium/es/clean-state-key.js' {
  declare module.exports: $Exports<'radium/es/clean-state-key'>;
}
declare module 'radium/es/components/style-root.js' {
  declare module.exports: $Exports<'radium/es/components/style-root'>;
}
declare module 'radium/es/components/style-sheet.js' {
  declare module.exports: $Exports<'radium/es/components/style-sheet'>;
}
declare module 'radium/es/components/style.js' {
  declare module.exports: $Exports<'radium/es/components/style'>;
}
declare module 'radium/es/config.js' {
  declare module.exports: $Exports<'radium/es/config'>;
}
declare module 'radium/es/css-rule-set-to-string.js' {
  declare module.exports: $Exports<'radium/es/css-rule-set-to-string'>;
}
declare module 'radium/es/enhancer.js' {
  declare module.exports: $Exports<'radium/es/enhancer'>;
}
declare module 'radium/es/get-radium-style-state.js' {
  declare module.exports: $Exports<'radium/es/get-radium-style-state'>;
}
declare module 'radium/es/get-state-key.js' {
  declare module.exports: $Exports<'radium/es/get-state-key'>;
}
declare module 'radium/es/get-state.js' {
  declare module.exports: $Exports<'radium/es/get-state'>;
}
declare module 'radium/es/hash.js' {
  declare module.exports: $Exports<'radium/es/hash'>;
}
declare module 'radium/es/index.js' {
  declare module.exports: $Exports<'radium/es/index'>;
}
declare module 'radium/es/keyframes.js' {
  declare module.exports: $Exports<'radium/es/keyframes'>;
}
declare module 'radium/es/map-object.js' {
  declare module.exports: $Exports<'radium/es/map-object'>;
}
declare module 'radium/es/merge-styles.js' {
  declare module.exports: $Exports<'radium/es/merge-styles'>;
}
declare module 'radium/es/plugins/check-props-plugin.js' {
  declare module.exports: $Exports<'radium/es/plugins/check-props-plugin'>;
}
declare module 'radium/es/plugins/index.js' {
  declare module.exports: $Exports<'radium/es/plugins/index'>;
}
declare module 'radium/es/plugins/keyframes-plugin.js' {
  declare module.exports: $Exports<'radium/es/plugins/keyframes-plugin'>;
}
declare module 'radium/es/plugins/merge-style-array-plugin.js' {
  declare module.exports: $Exports<'radium/es/plugins/merge-style-array-plugin'>;
}
declare module 'radium/es/plugins/mouse-up-listener.js' {
  declare module.exports: $Exports<'radium/es/plugins/mouse-up-listener'>;
}
declare module 'radium/es/plugins/prefix-plugin.js' {
  declare module.exports: $Exports<'radium/es/plugins/prefix-plugin'>;
}
declare module 'radium/es/plugins/remove-nested-styles-plugin.js' {
  declare module.exports: $Exports<'radium/es/plugins/remove-nested-styles-plugin'>;
}
declare module 'radium/es/plugins/resolve-interaction-styles-plugin.js' {
  declare module.exports: $Exports<'radium/es/plugins/resolve-interaction-styles-plugin'>;
}
declare module 'radium/es/plugins/resolve-media-queries-plugin.js' {
  declare module.exports: $Exports<'radium/es/plugins/resolve-media-queries-plugin'>;
}
declare module 'radium/es/plugins/visited-plugin.js' {
  declare module.exports: $Exports<'radium/es/plugins/visited-plugin'>;
}
declare module 'radium/es/prefix-data/dynamic.js' {
  declare module.exports: $Exports<'radium/es/prefix-data/dynamic'>;
}
declare module 'radium/es/prefix-data/static.js' {
  declare module.exports: $Exports<'radium/es/prefix-data/static'>;
}
declare module 'radium/es/prefixer.js' {
  declare module.exports: $Exports<'radium/es/prefixer'>;
}
declare module 'radium/es/resolve-styles.js' {
  declare module.exports: $Exports<'radium/es/resolve-styles'>;
}
declare module 'radium/es/style-keeper.js' {
  declare module.exports: $Exports<'radium/es/style-keeper'>;
}
declare module 'radium/es/test-helpers.js' {
  declare module.exports: $Exports<'radium/es/test-helpers'>;
}
declare module 'radium/index' {
  declare module.exports: $Exports<'radium'>;
}
declare module 'radium/index.js' {
  declare module.exports: $Exports<'radium'>;
}
declare module 'radium/lib/append-important-to-each-value.js' {
  declare module.exports: $Exports<'radium/lib/append-important-to-each-value'>;
}
declare module 'radium/lib/append-px-if-needed.js' {
  declare module.exports: $Exports<'radium/lib/append-px-if-needed'>;
}
declare module 'radium/lib/camel-case-props-to-dash-case.js' {
  declare module.exports: $Exports<'radium/lib/camel-case-props-to-dash-case'>;
}
declare module 'radium/lib/clean-state-key.js' {
  declare module.exports: $Exports<'radium/lib/clean-state-key'>;
}
declare module 'radium/lib/components/style-root.js' {
  declare module.exports: $Exports<'radium/lib/components/style-root'>;
}
declare module 'radium/lib/components/style-sheet.js' {
  declare module.exports: $Exports<'radium/lib/components/style-sheet'>;
}
declare module 'radium/lib/components/style.js' {
  declare module.exports: $Exports<'radium/lib/components/style'>;
}
declare module 'radium/lib/config.js' {
  declare module.exports: $Exports<'radium/lib/config'>;
}
declare module 'radium/lib/css-rule-set-to-string.js' {
  declare module.exports: $Exports<'radium/lib/css-rule-set-to-string'>;
}
declare module 'radium/lib/enhancer.js' {
  declare module.exports: $Exports<'radium/lib/enhancer'>;
}
declare module 'radium/lib/get-radium-style-state.js' {
  declare module.exports: $Exports<'radium/lib/get-radium-style-state'>;
}
declare module 'radium/lib/get-state-key.js' {
  declare module.exports: $Exports<'radium/lib/get-state-key'>;
}
declare module 'radium/lib/get-state.js' {
  declare module.exports: $Exports<'radium/lib/get-state'>;
}
declare module 'radium/lib/hash.js' {
  declare module.exports: $Exports<'radium/lib/hash'>;
}
declare module 'radium/lib/index.js' {
  declare module.exports: $Exports<'radium/lib/index'>;
}
declare module 'radium/lib/keyframes.js' {
  declare module.exports: $Exports<'radium/lib/keyframes'>;
}
declare module 'radium/lib/map-object.js' {
  declare module.exports: $Exports<'radium/lib/map-object'>;
}
declare module 'radium/lib/merge-styles.js' {
  declare module.exports: $Exports<'radium/lib/merge-styles'>;
}
declare module 'radium/lib/plugins/check-props-plugin.js' {
  declare module.exports: $Exports<'radium/lib/plugins/check-props-plugin'>;
}
declare module 'radium/lib/plugins/index.js' {
  declare module.exports: $Exports<'radium/lib/plugins/index'>;
}
declare module 'radium/lib/plugins/keyframes-plugin.js' {
  declare module.exports: $Exports<'radium/lib/plugins/keyframes-plugin'>;
}
declare module 'radium/lib/plugins/merge-style-array-plugin.js' {
  declare module.exports: $Exports<'radium/lib/plugins/merge-style-array-plugin'>;
}
declare module 'radium/lib/plugins/mouse-up-listener.js' {
  declare module.exports: $Exports<'radium/lib/plugins/mouse-up-listener'>;
}
declare module 'radium/lib/plugins/prefix-plugin.js' {
  declare module.exports: $Exports<'radium/lib/plugins/prefix-plugin'>;
}
declare module 'radium/lib/plugins/remove-nested-styles-plugin.js' {
  declare module.exports: $Exports<'radium/lib/plugins/remove-nested-styles-plugin'>;
}
declare module 'radium/lib/plugins/resolve-interaction-styles-plugin.js' {
  declare module.exports: $Exports<'radium/lib/plugins/resolve-interaction-styles-plugin'>;
}
declare module 'radium/lib/plugins/resolve-media-queries-plugin.js' {
  declare module.exports: $Exports<'radium/lib/plugins/resolve-media-queries-plugin'>;
}
declare module 'radium/lib/plugins/visited-plugin.js' {
  declare module.exports: $Exports<'radium/lib/plugins/visited-plugin'>;
}
declare module 'radium/lib/prefix-data/dynamic.js' {
  declare module.exports: $Exports<'radium/lib/prefix-data/dynamic'>;
}
declare module 'radium/lib/prefix-data/static.js' {
  declare module.exports: $Exports<'radium/lib/prefix-data/static'>;
}
declare module 'radium/lib/prefixer.js' {
  declare module.exports: $Exports<'radium/lib/prefixer'>;
}
declare module 'radium/lib/resolve-styles.js' {
  declare module.exports: $Exports<'radium/lib/resolve-styles'>;
}
declare module 'radium/lib/style-keeper.js' {
  declare module.exports: $Exports<'radium/lib/style-keeper'>;
}
declare module 'radium/lib/test-helpers.js' {
  declare module.exports: $Exports<'radium/lib/test-helpers'>;
}
declare module 'radium/src/__mocks__/exenv.js' {
  declare module.exports: $Exports<'radium/src/__mocks__/exenv'>;
}
declare module 'radium/src/__mocks__/prefixer.js' {
  declare module.exports: $Exports<'radium/src/__mocks__/prefixer'>;
}
declare module 'radium/src/__tests__/camel-case-props-to-dash-case-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/camel-case-props-to-dash-case-test'>;
}
declare module 'radium/src/__tests__/clean-state-key-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/clean-state-key-test'>;
}
declare module 'radium/src/__tests__/enhancer-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/enhancer-test'>;
}
declare module 'radium/src/__tests__/get-radium-style-state-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/get-radium-style-state-test'>;
}
declare module 'radium/src/__tests__/get-state-key-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/get-state-key-test'>;
}
declare module 'radium/src/__tests__/get-state-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/get-state-test'>;
}
declare module 'radium/src/__tests__/keyframes-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/keyframes-test'>;
}
declare module 'radium/src/__tests__/media-query-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/media-query-test'>;
}
declare module 'radium/src/__tests__/radium-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/radium-test'>;
}
declare module 'radium/src/__tests__/remove-nested-styles-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/remove-nested-styles-test'>;
}
declare module 'radium/src/__tests__/resolve-styles-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/resolve-styles-test'>;
}
declare module 'radium/src/__tests__/style-component-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/style-component-test'>;
}
declare module 'radium/src/__tests__/visited-test.js' {
  declare module.exports: $Exports<'radium/src/__tests__/visited-test'>;
}
declare module 'radium/src/append-important-to-each-value.js' {
  declare module.exports: $Exports<'radium/src/append-important-to-each-value'>;
}
declare module 'radium/src/append-px-if-needed.js' {
  declare module.exports: $Exports<'radium/src/append-px-if-needed'>;
}
declare module 'radium/src/camel-case-props-to-dash-case.js' {
  declare module.exports: $Exports<'radium/src/camel-case-props-to-dash-case'>;
}
declare module 'radium/src/clean-state-key.js' {
  declare module.exports: $Exports<'radium/src/clean-state-key'>;
}
declare module 'radium/src/components/style-root.js' {
  declare module.exports: $Exports<'radium/src/components/style-root'>;
}
declare module 'radium/src/components/style-sheet.js' {
  declare module.exports: $Exports<'radium/src/components/style-sheet'>;
}
declare module 'radium/src/components/style.js' {
  declare module.exports: $Exports<'radium/src/components/style'>;
}
declare module 'radium/src/config.js' {
  declare module.exports: $Exports<'radium/src/config'>;
}
declare module 'radium/src/css-rule-set-to-string.js' {
  declare module.exports: $Exports<'radium/src/css-rule-set-to-string'>;
}
declare module 'radium/src/enhancer.js' {
  declare module.exports: $Exports<'radium/src/enhancer'>;
}
declare module 'radium/src/get-radium-style-state.js' {
  declare module.exports: $Exports<'radium/src/get-radium-style-state'>;
}
declare module 'radium/src/get-state-key.js' {
  declare module.exports: $Exports<'radium/src/get-state-key'>;
}
declare module 'radium/src/get-state.js' {
  declare module.exports: $Exports<'radium/src/get-state'>;
}
declare module 'radium/src/hash.js' {
  declare module.exports: $Exports<'radium/src/hash'>;
}
declare module 'radium/src/index.js' {
  declare module.exports: $Exports<'radium/src/index'>;
}
declare module 'radium/src/keyframes.js' {
  declare module.exports: $Exports<'radium/src/keyframes'>;
}
declare module 'radium/src/map-object.js' {
  declare module.exports: $Exports<'radium/src/map-object'>;
}
declare module 'radium/src/merge-styles.js' {
  declare module.exports: $Exports<'radium/src/merge-styles'>;
}
declare module 'radium/src/plugins/check-props-plugin.js' {
  declare module.exports: $Exports<'radium/src/plugins/check-props-plugin'>;
}
declare module 'radium/src/plugins/index.js' {
  declare module.exports: $Exports<'radium/src/plugins/index'>;
}
declare module 'radium/src/plugins/keyframes-plugin.js' {
  declare module.exports: $Exports<'radium/src/plugins/keyframes-plugin'>;
}
declare module 'radium/src/plugins/merge-style-array-plugin.js' {
  declare module.exports: $Exports<'radium/src/plugins/merge-style-array-plugin'>;
}
declare module 'radium/src/plugins/mouse-up-listener.js' {
  declare module.exports: $Exports<'radium/src/plugins/mouse-up-listener'>;
}
declare module 'radium/src/plugins/prefix-plugin.js' {
  declare module.exports: $Exports<'radium/src/plugins/prefix-plugin'>;
}
declare module 'radium/src/plugins/remove-nested-styles-plugin.js' {
  declare module.exports: $Exports<'radium/src/plugins/remove-nested-styles-plugin'>;
}
declare module 'radium/src/plugins/resolve-interaction-styles-plugin.js' {
  declare module.exports: $Exports<'radium/src/plugins/resolve-interaction-styles-plugin'>;
}
declare module 'radium/src/plugins/resolve-media-queries-plugin.js' {
  declare module.exports: $Exports<'radium/src/plugins/resolve-media-queries-plugin'>;
}
declare module 'radium/src/plugins/visited-plugin.js' {
  declare module.exports: $Exports<'radium/src/plugins/visited-plugin'>;
}
declare module 'radium/src/prefix-data/dynamic.js' {
  declare module.exports: $Exports<'radium/src/prefix-data/dynamic'>;
}
declare module 'radium/src/prefix-data/static.js' {
  declare module.exports: $Exports<'radium/src/prefix-data/static'>;
}
declare module 'radium/src/prefixer.js' {
  declare module.exports: $Exports<'radium/src/prefixer'>;
}
declare module 'radium/src/resolve-styles.js' {
  declare module.exports: $Exports<'radium/src/resolve-styles'>;
}
declare module 'radium/src/style-keeper.js' {
  declare module.exports: $Exports<'radium/src/style-keeper'>;
}
declare module 'radium/src/test-helpers.js' {
  declare module.exports: $Exports<'radium/src/test-helpers'>;
}
